// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMs8eh9UUkXu7LQafYSBDIKQU9M_Y3bVU',
    appId: '1:918856564159:web:0a7489aaac5b98a786350a',
    messagingSenderId: '918856564159',
    projectId: 'sharefood-cfe6f',
    authDomain: 'sharefood-cfe6f.firebaseapp.com',
    storageBucket: 'sharefood-cfe6f.firebasestorage.app',
    measurementId: 'G-R9EBRVS1KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9qPRV3q2u1FvNiwBUE-R8yEulfemngHg',
    appId: '1:918856564159:android:eb58d9e8b380749d86350a',
    messagingSenderId: '918856564159',
    projectId: 'sharefood-cfe6f',
    storageBucket: 'sharefood-cfe6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlE8Ng1edm2DMT3asMm27x-ZtvEpv5f8Y',
    appId: '1:918856564159:ios:4405e88921654c2886350a',
    messagingSenderId: '918856564159',
    projectId: 'sharefood-cfe6f',
    storageBucket: 'sharefood-cfe6f.firebasestorage.app',
    iosBundleId: 'com.sharefood.sharefood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlE8Ng1edm2DMT3asMm27x-ZtvEpv5f8Y',
    appId: '1:918856564159:ios:4405e88921654c2886350a',
    messagingSenderId: '918856564159',
    projectId: 'sharefood-cfe6f',
    storageBucket: 'sharefood-cfe6f.firebasestorage.app',
    iosBundleId: 'com.sharefood.sharefood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMs8eh9UUkXu7LQafYSBDIKQU9M_Y3bVU',
    appId: '1:918856564159:web:5f1ef2613d12a53a86350a',
    messagingSenderId: '918856564159',
    projectId: 'sharefood-cfe6f',
    authDomain: 'sharefood-cfe6f.firebaseapp.com',
    storageBucket: 'sharefood-cfe6f.firebasestorage.app',
    measurementId: 'G-5CRYKET1B7',
  );
}
