// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtZGr8WLl_PLnk7jBLsw6X4M0h-IkNDiQ',
    appId: '1:935775560239:web:672ce1290ac9fdc9f6dcda',
    messagingSenderId: '935775560239',
    projectId: 'sharefoodfaccat',
    authDomain: 'sharefoodfaccat.firebaseapp.com',
    storageBucket: 'sharefoodfaccat.firebasestorage.app',
    measurementId: 'G-MPMF8D9FR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcekmNK9uNNmUJ4HjUAHFo_XWbevsfxMk',
    appId: '1:935775560239:android:8acdb524c42829b3f6dcda',
    messagingSenderId: '935775560239',
    projectId: 'sharefoodfaccat',
    storageBucket: 'sharefoodfaccat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeFHwbtjpjHav8Beln6u1Dy0Nx8OvNdBQ',
    appId: '1:935775560239:ios:b495edf36e8e3681f6dcda',
    messagingSenderId: '935775560239',
    projectId: 'sharefoodfaccat',
    storageBucket: 'sharefoodfaccat.firebasestorage.app',
    iosBundleId: 'com.sharefood.sharefood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeFHwbtjpjHav8Beln6u1Dy0Nx8OvNdBQ',
    appId: '1:935775560239:ios:b495edf36e8e3681f6dcda',
    messagingSenderId: '935775560239',
    projectId: 'sharefoodfaccat',
    storageBucket: 'sharefoodfaccat.firebasestorage.app',
    iosBundleId: 'com.sharefood.sharefood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtZGr8WLl_PLnk7jBLsw6X4M0h-IkNDiQ',
    appId: '1:935775560239:web:58bc6edff4ae2de6f6dcda',
    messagingSenderId: '935775560239',
    projectId: 'sharefoodfaccat',
    authDomain: 'sharefoodfaccat.firebaseapp.com',
    storageBucket: 'sharefoodfaccat.firebasestorage.app',
    measurementId: 'G-CLXGME3V5L',
  );

}